Don't destroy patches.
Instead fall back to a normal git merge-file.

Closes #2

diff --git a/clang-format-merge b/clang-format-merge
--- a/clang-format-merge
+++ b/clang-format-merge
@@ -22,7 +22,13 @@ function format() {
     # -assume-filename only works with stdin, for whatever reason.
     cat "$1" | clang-format "-assume-filename=$REPO_PATH" > "$1.tmp"
   fi
-  if [ -s "$1.tmp" ]; then
+  if [ $? -ne 0 ]; then
+    # We let the thing keep going, this will end up in `git merge-file` and
+    # that will error out if there are conflicts.
+    echo "clang-format failed, make sure you run ./mach clang-format manually at least once"
+    cat "$1.tmp"
+    rm "$1.tmp"
+  elif [ -s "$1.tmp" ]; then
     mv "$1.tmp" "$1"
   else
     rm "$1.tmp"
